/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NossasSolucoesIndexRouteImport } from './routes/nossas-solucoes.index'
import { Route as NossasSolucoesPecasDeReposicaoRouteImport } from './routes/nossas-solucoes.pecas-de-reposicao'
import { Route as NossasSolucoesCategoriaIndexRouteImport } from './routes/nossas-solucoes.$categoria.index'
import { Route as NossasSolucoesCategoriaProdutoRouteImport } from './routes/nossas-solucoes.$categoria.$produto'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NossasSolucoesIndexRoute = NossasSolucoesIndexRouteImport.update({
  id: '/nossas-solucoes/',
  path: '/nossas-solucoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NossasSolucoesPecasDeReposicaoRoute =
  NossasSolucoesPecasDeReposicaoRouteImport.update({
    id: '/nossas-solucoes/pecas-de-reposicao',
    path: '/nossas-solucoes/pecas-de-reposicao',
    getParentRoute: () => rootRouteImport,
  } as any)
const NossasSolucoesCategoriaIndexRoute =
  NossasSolucoesCategoriaIndexRouteImport.update({
    id: '/nossas-solucoes/$categoria/',
    path: '/nossas-solucoes/$categoria/',
    getParentRoute: () => rootRouteImport,
  } as any)
const NossasSolucoesCategoriaProdutoRoute =
  NossasSolucoesCategoriaProdutoRouteImport.update({
    id: '/nossas-solucoes/$categoria/$produto',
    path: '/nossas-solucoes/$categoria/$produto',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/nossas-solucoes/pecas-de-reposicao': typeof NossasSolucoesPecasDeReposicaoRoute
  '/nossas-solucoes/': typeof NossasSolucoesIndexRoute
  '/nossas-solucoes/$categoria/$produto': typeof NossasSolucoesCategoriaProdutoRoute
  '/nossas-solucoes/$categoria/': typeof NossasSolucoesCategoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/nossas-solucoes/pecas-de-reposicao': typeof NossasSolucoesPecasDeReposicaoRoute
  '/nossas-solucoes': typeof NossasSolucoesIndexRoute
  '/nossas-solucoes/$categoria/$produto': typeof NossasSolucoesCategoriaProdutoRoute
  '/nossas-solucoes/$categoria': typeof NossasSolucoesCategoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/nossas-solucoes/pecas-de-reposicao': typeof NossasSolucoesPecasDeReposicaoRoute
  '/nossas-solucoes/': typeof NossasSolucoesIndexRoute
  '/nossas-solucoes/$categoria/$produto': typeof NossasSolucoesCategoriaProdutoRoute
  '/nossas-solucoes/$categoria/': typeof NossasSolucoesCategoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/nossas-solucoes/pecas-de-reposicao'
    | '/nossas-solucoes/'
    | '/nossas-solucoes/$categoria/$produto'
    | '/nossas-solucoes/$categoria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/nossas-solucoes/pecas-de-reposicao'
    | '/nossas-solucoes'
    | '/nossas-solucoes/$categoria/$produto'
    | '/nossas-solucoes/$categoria'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/nossas-solucoes/pecas-de-reposicao'
    | '/nossas-solucoes/'
    | '/nossas-solucoes/$categoria/$produto'
    | '/nossas-solucoes/$categoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  ContatoRoute: typeof ContatoRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  NossasSolucoesPecasDeReposicaoRoute: typeof NossasSolucoesPecasDeReposicaoRoute
  NossasSolucoesIndexRoute: typeof NossasSolucoesIndexRoute
  NossasSolucoesCategoriaProdutoRoute: typeof NossasSolucoesCategoriaProdutoRoute
  NossasSolucoesCategoriaIndexRoute: typeof NossasSolucoesCategoriaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossas-solucoes/': {
      id: '/nossas-solucoes/'
      path: '/nossas-solucoes'
      fullPath: '/nossas-solucoes/'
      preLoaderRoute: typeof NossasSolucoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossas-solucoes/pecas-de-reposicao': {
      id: '/nossas-solucoes/pecas-de-reposicao'
      path: '/nossas-solucoes/pecas-de-reposicao'
      fullPath: '/nossas-solucoes/pecas-de-reposicao'
      preLoaderRoute: typeof NossasSolucoesPecasDeReposicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossas-solucoes/$categoria/': {
      id: '/nossas-solucoes/$categoria/'
      path: '/nossas-solucoes/$categoria'
      fullPath: '/nossas-solucoes/$categoria/'
      preLoaderRoute: typeof NossasSolucoesCategoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossas-solucoes/$categoria/$produto': {
      id: '/nossas-solucoes/$categoria/$produto'
      path: '/nossas-solucoes/$categoria/$produto'
      fullPath: '/nossas-solucoes/$categoria/$produto'
      preLoaderRoute: typeof NossasSolucoesCategoriaProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  ContatoRoute: ContatoRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  NossasSolucoesPecasDeReposicaoRoute: NossasSolucoesPecasDeReposicaoRoute,
  NossasSolucoesIndexRoute: NossasSolucoesIndexRoute,
  NossasSolucoesCategoriaProdutoRoute: NossasSolucoesCategoriaProdutoRoute,
  NossasSolucoesCategoriaIndexRoute: NossasSolucoesCategoriaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
